export const data = [
    {
        id:1,
        name:"Kathakali",
        img1:"https://thumbs.dreamstime.com/b/kathakali-performer-applying-face-make-up-fort-cochin-december-unidentified-prior-to-performance-december-south-india-72993482.jpg",
        images:"https://www.shutterstock.com/image-photo/kochi-india-may-28-unidentified-260nw-1865794933.jpg",
        description:"Kathakali is an evolved dance form popular in the South Indian state of Kerala.",
        detail:"Kathakali an important genre in the Indian classical dance form, is associated with storytelling form of this art. It is the dance drama from the south Indian state of Kerala. Similar to other Indian classical dance arts, the story in Kathakali is also communicated to audience through excellent footwork and impressive gestures of face and hands complimented with music and vocal performance. However it can be distinguished from the others through the intricate and vivid make-up, unique face masks and costumes worn by dancers as also from their style and movements that reflect the age-old martial arts and athletic conventions prevalent in Kerala and surrounding regions. Traditionally performed by male dancers, it developed in courts and theatres of Hindu regions contrary to other Indian classical dances which predominantly developed in Hindu temples and monastic schools.",
    },
    
    {
        id:2,
        name:"Padayani",
        img1:"https://i.pinimg.com/736x/96/3d/8e/963d8ea5cecc5eb7e0ed068b04ab0e0b.jpg",
        images:"https://www.shutterstock.com/shutterstock/photos/1705502662/display_1500/stock-photo-padayani-also-called-padeni-is-a-traditional-folk-dance-and-a-ritual-art-from-the-central-portion-1705502662.jpg",
        description:"Padayani is a traditional folk dance and a ritual art from the central portion of the Indian state of Kerala.",
        detail:"Padayani, also known Padeni (from the Malayalam word for military formations), is a traditional folk dance and a ritual art from the central portion of the Indian state of Kerala. A ceremonial dance involving masks, it is an ancient ritual performed in Bhagavati temples. The dance is performed in honor of Bhadrakaali. Meaning, a 'row of warriors', Padayani is an art form that blends all music, dance, theatre, satire, facial masks, and paintings. It is part of worship of Bhadrakali and is staged in temples dedicated to the goddess from mid-December to mid-May.Padayani is unique to central Travancore, comprising the Pathanamthitta and kottayam districts of Kerala. Padayani is regarded as a remnant of the Dravidian forms of worship that existed before the advent of Brahmanism. Padayani is like Theyyam in north Kerala. The percussion instruments used in Patayani are patayani thappu, chenda, para and kumbham. Padayani at Puthukulangara Devi Temple, Othera, Pathanamthitta District is also famous. Here Bhairavi kolam which is on last day of festival is very famous. For making that 1001 bark of arecanut palm tree is used.",
    
    },
    {
        id:3,
        name:"Kadhak",
        img1:"https://i.pinimg.com/236x/92/7d/8f/927d8f5d8a79ca7852b52f91727ce435.jpg",
        images:"https://www.shutterstock.com/image-photo/senior-renowned-kathak-artist-does-260nw-1357301897.jpg",
        description:"Kathak is one among the eight Indian classical dance forms. The word 'Kathak' has its origins from the Sanskrit word Katha which means story.",
        detail:"Kathak, one of the most elegant dance forms of India, revolves around the concept of storytelling. An art form with inexplicable charm, mesmerising footwork, and graceful movements, Kathak figures among the eight Indian classical dance forms and is the only dance form from northern India.Kathak has over time evolved into three styles namely Classical, Contemporary and Sufi. It charms and captivates people with its swift pirouettes, unique rhythmic virtuosity and lyrical exploration of romantic as well as devotional poetry. The sharp yet fluid movements synchronised with deft and brisk spins, unleashes a visual splendour onstage taking audiences on a spiritual journey.",
    },
    {
        id:4,
        name:"Theyyam",
        img1:"https://mir-s3-cdn-cf.behance.net/project_modules/2800_opt_1/bc184f78391167.5ca3980fb5fe1.jpg",
        images:"https://www.shutterstock.com/image-photo/thiruvanathapuram-kerala-india-february-27-260nw-1183606984.jpg",
        description:"Theyyam is a famous ritual art form that originated in North Kerala which brings to life the great stories of our State.",
        detail:"The great stories of Kerala are often retold using art forms. It is here that our legends truly come to life. Theyyam is a famous ritual art form that originated in North Kerala which brings to life the great stories of our State. It encompasses dance, mime and music. It exalts the beliefs of the ancient tribals who gave a lot of importance to the worship of heroes and the spirits of their ancestors. The ceremonious dance is accompanied by the chorus of such musical instruments as Chenda, Elathalam, Kurumkuzal and Veekkuchenda. There are over 400 separate Theyyams, each with their own music, style and choreography. The most prominent among these are Raktha Chamundi, Kari Chamundi, Muchilottu Bhagavathi, Wayanadu Kulaven, Gulikan and Pottan.",
    },
    {
        id:5,
        name:"Mohiniyattam",
        img1:"https://www.shutterstock.com/image-photo/bengaluru-india-april-6th-mohiniattam-260nw-1363271600.jpg",
        images:"https://www.shutterstock.com/image-photo/bengaluru-india-april-6th-mohiniattam-260nw-1363269032.jpg",
        description:"Mohiniyattam is a lasya subgenre of dance, performed in the Kaisiki vritti (graceful style),",
        detail:"Mohiniyattam (Mohiniattam) is a classical dance form of Kerala in South India. The origin and popularity of this dance form is closely tagged to the great Tamil dance master Vadivelu, one of the Thanjavur quartets. One among the eight Indian classical dance forms, Mohiniyattam is a graceful dance to watch and is a solo recital by women. The term Mohiniyattam comes from the words mohini meaning a woman who enchants onlookers and aattam meaning graceful and sensuous body movements. Thus, the word Mohiniyattam literally means - dance of the enchantress.",
    },
    {
        id:6,
        name:"Kuchipodi",
        img1:"https://i.pinimg.com/736x/9f/43/35/9f43353c6e9ea4a9faf40c9e3d5b710c.jpg",
        images:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQN-gs8fK_NGB3PO-hgAG3STbbJOLUn5wMELA&usqp=CAU",
        description:"Kuchipudi is indigenous to the state of Andhra Pradesh and differs from the other five classical styles by the inclusion of singing.",
        detail:"Kuchipudi is indigenous to the state of Andhra Pradesh and differs from the other five classical styles by the inclusion of singing. Kuchipudi originated in the 17th century with the creation by Sidhyendra Yogi of the dance-drama Bhama Kalapam, a story of Satyabhāma, the charming but jealous wife of the god Krishna",
    },
    {
        id:7,
        name:"Pavakoothu",
        img1:"https://image.shutterstock.com/image-photo/koonathara-palakkad-kerala-india-january-260nw-2253925835.jpg",
        images:"https://image.shutterstock.com/image-photo/koonathara-palakkad-kerala-india-january-260nw-2253925835.jpg",
        description:"The pava koothu “dance” or “puppet show” represents the victory dance of the goddess Lakshmi after destroying the demons",
        detail:"Tholppava (Thol means leather, Pava means puppet) are moved with the help of strings, and their shadows are depicted on a screen with the help of a row of oil lamps in the background. The story of Tholppavakoothu performance is from the Indian epic, Ramayana. In the olden days it was performed elaborately over a period of forty-one days. The narrative used for the performance is a mixture of prose and poetry called Adalpattu.",
    },
    {
        id:8,
        name:"madhubani",
        img1:"https://cdn.shopify.com/s/files/1/0331/6806/4645/products/peacock-madhubani-painting-a5-frame-paintings-713501.jpg?v=1663626505",
        images:"https://www.shutterstock.com/image-vector/indian-folk-painting-madhubani-peacock-260nw-621198350.jpg",
        description:"Mithila painting is a style of painting practiced in the Mithila region of India and Nepal. ",
        detail:"Painting is a mode of expression for human thought. In the Indian context, art emerged when homo sapiens painted on mud surface through twigs, fingers or bone points which could not withstand the ravages of time. The earliest available examples found from the Mesolithic caves evolved their way with their continous presence in the daily lives of people. So developed the wall painting tradition of India, of which Madhubani is a famous name",
    },
    {
        id:9,
        name:"Bharathanattyam",
        img1:"https://t3.ftcdn.net/jpg/04/67/58/22/360_F_467582239_Y3vnaMCkrRA3xKqYIQnWgRerhIeYz3s6.jpg",
        images:"https://www.shutterstock.com/image-photo/portrait-white-girl-indian-classical-260nw-1411485308.jpg",
        description:"Bharatanatyam, a pre-eminent Indian classical dance form presumably the oldest classical dance heritage of India ",
        detail:"Bharatanatyam is traditionally a team performance art that consists of a solo dancer, accompanied by musicians and one or more singers. The theory behind the musical notes, vocal performance and the dance movement trace back to the ancient Natya Shastra, and many Sanskrit and Tamil texts such as the Abhinaya Darpana.",
    },
    {
        id:10,
        name:"Pulikali",
        img1:"https://images.indianexpress.com/2019/10/Page5_main_759.jpg",
        images:"https://image.shutterstock.com/image-photo/thrissur-india-sep-07body-painted-260nw-715589629.jpg",
        description:"Puli kali (Meaning: Leopard Dance) is a recreational folk art from the state of Kerala, India.",
        detail:"Puli kali (Meaning: Leopard Dance) is a recreational folk art from the state of Kerala, India. It is performed by trained artists to entertain people on the occasion of Onam, an annual harvest festival, celebrated mainly in the Indian state of Kerala.",
    },
    {
        id:11,
        name:"Kalari",
        img1:"https://www.keralatourism.org/images/enchanting_kerala/large/kalaripayattu20150821085515_559_1.jpg",
        images:"https://www.shutterstock.com/image-photo/kalaripayattu-artists-performing-keralas-oldest-260nw-1458768764.jpg",
        description:"Considered among the oldest and most scientific martial arts in the world, Kalaripayattu was developed in Kerala. Lauded as the pride of Kerala, it is acknowledged and respected across the world. The training begins with an oil massage of the entire body until it is agile and supple",
    },
    {
        id:12,
        name:"Nadodinirtham",
        img1:"https://www.venkatphotography.com/img/s/v-10/p1003988-3.jpg",
        images:"https://www.shutterstock.com/image-photo/beautiful-young-indian-girl-child-260nw-1577795881.jpg",
        description:"nadodi nritham is an art form performed in the costume of tribes and villagers. Nadodis often perform different art items as a part of their celebrations and happiness.",
        detail:"Each state is associated with some form of folk and tribal art forms exhibiting its culture. Kerala includes numerous colourful folk dances. Let me mention the names of a few such rare art forms before proceeding further. Velakali, Ammanottam, Ezhamathukali, Kol kali, Dappu kali, Poorakali, Pen tharumo nritham (will you give me a bride), Thiyaattu, Padayani, Cherumar kali, Pallukali, Parayan thira, Kolam Thullal, Bhootham thullal, Thidambu nritham and many more. Most of such dance forms are deeply rooted in tribal culture, mostly of Wayanad and Malabar areas. I just want to give a small note on ‘nadodi nritham’ played on stage for competitions and purely for entertaining purposes",
    }
    ]
    